// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AllottedDetail: typeof import('./src/components/AllottedDetail.vue')['default']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuDivider: typeof import('ant-design-vue/es')['MenuDivider']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    APopconfirm: typeof import('ant-design-vue/es')['Popconfirm']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    ATypographyParagraph: typeof import('ant-design-vue/es')['TypographyParagraph']
    ATypographyTitle: typeof import('ant-design-vue/es')['TypographyTitle']
    BenefitsCard: typeof import('./src/components/benefitsCard/BenefitsCard.vue')['default']
    CoinCard: typeof import('./src/components/coinCard/CoinCard.vue')['default']
    CoinPairList: typeof import('./src/components/coinPairList/CoinPairList.vue')['default']
    CoolCatInfo: typeof import('./src/components/projectInfo/CoolCatInfo.vue')['default']
    CosmicHorizonInfo: typeof import('./src/components/projectInfo/CosmicHorizonInfo.vue')['default']
    CraftInfo: typeof import('./src/components/projectInfo/CraftInfo.vue')['default']
    CronusInfo: typeof import('./src/components/projectInfo/CronusInfo.vue')['default']
    Demo: typeof import('./src/components/projectInfo/Demo.vue')['default']
    DesmosInfo: typeof import('./src/components/projectInfo/DesmosInfo.vue')['default']
    DiffusionInfo: typeof import('./src/components/projectInfo/DiffusionInfo.vue')['default']
    ExswapInfo: typeof import('./src/components/projectInfo/ExswapInfo.vue')['default']
    Footer: typeof import('./src/components/footer/Footer.vue')['default']
    FortisInfo: typeof import('./src/components/projectInfo/FortisInfo.vue')['default']
    GravityInfo: typeof import('./src/components/projectInfo/GravityInfo.vue')['default']
    HansumInfo: typeof import('./src/components/projectInfo/HansumInfo.vue')['default']
    HopeInfo: typeof import('./src/components/projectInfo/HopeInfo.vue')['default']
    Icon: typeof import('./src/components/Icon.vue')['default']
    KLine: typeof import('./src/components/kLine/KLine.vue')['default']
    LikeInfo: typeof import('./src/components/projectInfo/LikeInfo.vue')['default']
    ManageProfile: typeof import('./src/components/ManageProfile.vue')['default']
    Nav: typeof import('./src/components/nav/Nav.vue')['default']
    NetaInfo: typeof import('./src/components/projectInfo/NetaInfo.vue')['default']
    ProjectCard: typeof import('./src/components/ProjectCard.vue')['default']
    ProjectDetail: typeof import('./src/components/ProjectDetail.vue')['default']
    ProjectFooter: typeof import('./src/components/ProjectFooter.vue')['default']
    PstakeInfo: typeof import('./src/components/projectInfo/PstakeInfo.vue')['default']
    RacoonInfo: typeof import('./src/components/projectInfo/RacoonInfo.vue')['default']
    SenatusInfo: typeof import('./src/components/projectInfo/SenatusInfo.vue')['default']
  }
}

export { }
