// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BenefitsCardBenefitsCard: typeof import('./src/components/benefitsCard/BenefitsCard.vue')['default']
    CoinCardCoinCard: typeof import('./src/components/coinCard/CoinCard.vue')['default']
    CoinPairListCoinPairList: typeof import('./src/components/coinPairList/CoinPairList.vue')['default']
    CoinPairsCoinPairs: typeof import('./src/components/coinPairs/CoinPairs.vue')['default']
    FooterFooter: typeof import('./src/components/footer/Footer.vue')['default']
    KLineKLine: typeof import('./src/components/kLine/KLine.vue')['default']
    MessageMessage: typeof import('./src/components/message/Message.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NavNav: typeof import('./src/components/nav/Nav.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCountdown: typeof import('naive-ui')['NCountdown']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NIcon: typeof import('naive-ui')['NIcon']
    NIconWrapper: typeof import('naive-ui')['NIconWrapper']
    NList: typeof import('naive-ui')['NList']
    NListItem: typeof import('naive-ui')['NListItem']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    SubscribeSubscribe: typeof import('./src/components/subscribe/Subscribe.vue')['default']
  }
}

export { }
